import {readFile,writeFile} from 'node:fs/promises';
import vm from 'node:vm';
import {photoCard, detailPhoto, heroShowcase, flowPanel, processAccordion} from './src/visuals.mjs';
import {illustrations} from './src/illustrations.mjs';
import {refinePage} from './src/refinements.mjs';
for(const [name,svg] of Object.entries(illustrations)) await writeFile(new URL(`dist/assets/${name}`,import.meta.url),svg);
const original=await readFile(new URL('src/app-original.js',import.meta.url),'utf8');
const services=vm.runInNewContext(original.slice(0,original.indexOf('const $'))+';services');
const slugs=['plumbing-repairs','heating-cooling','drain-repairs','commercial-plumbing','bathroom-remodelling','gas-line-services'];
services.forEach((s,i)=>{s.slug=slugs[i];s.category=i===3?'business':i===4?'projects':'repairs'});
const icon=name=>`<svg class="icon" aria-hidden="true"><use href="#i-${name}"/></svg>`;
const serviceHeading=name=>name.includes(' & ')?name.replace(' & ',' &<br><span>'):'<span>'+name;
const escape=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const routes=[['index','Home'],['about','About'],['services','Services'],['process','How it works'],['reviews','Reviews'],['faq','FAQs'],['contact','Contact']];
const nav=current=>routes.map(([key,label])=>`<a href="${key}.html" ${current===key?'aria-current="page"':''}>${label}</a>`).join('');
const cards=(list=services)=>list.map(s=>photoCard(s,services.indexOf(s))).join('');
const cta=()=>`<section class="wrap page-cta reveal"><div><p class="eyebrow">YOUR NEXT CHAPTER</p><h2>Let’s get it sorted.</h2><p>A small fix or a bigger plan. Start with a conversation.</p></div><button class="button white" data-quote>Get a free quote</button></section>`;
const intro=(title,kicker,description)=>`<section class="wrap page-intro"><div class="breadcrumbs"><a href="index.html">Home</a><span>/</span><span>${kicker}</span></div><p class="eyebrow">${kicker.toUpperCase()}</p><h1>${title}</h1><p class="intro-description">${description}</p></section>`;
const faqs=[
 ['Services','What kinds of properties do you work on?','The range covers domestic and commercial plumbing, heating and property improvements. Tell the team about your property so they can confirm the right service.'],
 ['Planning','Where are you based?','TRST Maintenance is based at 149 Stringes Lane, Willenhall, WV13 1LW. Share your postcode with your enquiry so the team can confirm coverage.'],
 ['Quotes','Can I get a quote before booking?','Yes. Start with a free quote request and explain the work you need. The team can confirm whether a visit or more information is needed to prepare a quote.'],
 ['Planning','What if I need urgent help?','Call 01902 635925 to discuss your issue and confirm current availability. Calling is the most direct way to speak to the team about urgent work.'],
 ['Quotes','What should I include in my enquiry?','Include your postcode, property type, a short description of the issue or project, and how you would like to be contacted. Mention any timing requirements too.'],
 ['Services','Can I enquire about more than one service?','Yes. Describe all the work you have in mind. The team can discuss the scope and whether the tasks can be coordinated.'],
 ['Planning','Can you work around my business hours?','Include your opening hours and access arrangements in your enquiry. The team will need to confirm a suitable schedule with you.'],
 ['Quotes','Does an enquiry commit me to booking?','The proposed journey starts with a conversation. Agree the scope, price and timing directly with the team before arranging any work.'],
 ['Services','Do you help with bathroom projects?','Bathroom and remodelling enquiries are part of the service range. Describe the fixtures, layout changes or plumbing improvements you have in mind.']
];
let template=await readFile(new URL('src/template.html',import.meta.url),'utf8');
template=template.replace(/<a class="brand"[^>]*>.*?<\/a>/g,`<a class="brand original-brand" href="index.html" aria-label="TRST Maintenance home"><img src="assets/trst-logo.jpg" width="184" height="63" alt="TRST"><span class="original-brand-name">MAINTENANCE LTD</span></a>`);
template=template.replace('<link rel="stylesheet" href="styles.css">','<link rel="stylesheet" href="styles.css"><link rel="stylesheet" href="enhancements.css"><link rel="stylesheet" href="visuals.css">');
template=template.replace('<body>','<body><div class="reading-progress" aria-hidden="true"></div>');
template=template.replace(/<dialog id="service-dialog"[\s\S]*?<\/dialog>/,'');
template=template.replace(/<footer class="wrap">[\s\S]*?<\/footer>/,`<footer class="wrap"><div class="footer-top"><a class="brand original-brand" href="index.html" aria-label="TRST Maintenance home"><img src="assets/trst-logo.jpg" width="184" height="63" alt="TRST"><span class="original-brand-name">MAINTENANCE LTD</span></a><p>Good hands. Great results.</p><a href="#main" class="text-link">Back to top <span class="plus">+</span></a></div><nav class="footer-nav" aria-label="Footer navigation">${nav('')}</nav><div class="footer-bottom"><span>© 2026 TRST Maintenance Ltd.</span><span>Independent design concept · Demo quote form</span><button class="plain-link" id="concept-info">About this prototype</button></div><div class="agency-credit">Designed & developed by <a href="https://atarionsolutions.com/" target="_blank" rel="noopener noreferrer">Atarion Solutions <span aria-hidden="true">↗</span></a></div></footer>`);
template=template.replaceAll('href="#services"','href="services.html"').replaceAll('href="#about"','href="about.html"').replaceAll('href="#process"','href="process.html"').replaceAll('href="#contact"','href="contact.html"');
let home=template.match(/<main id="main">([\s\S]*?)<\/main>/)[1];
home=home.replace('<div class="service-grid" id="service-grid"></div>',`<div class="service-grid" id="service-grid">${cards()}</div>`);
home=home.replace('<p class="hero-description">',`<div class="audience-switch" role="group" aria-label="Choose property type"><button aria-pressed="true" data-audience="home">For your home</button><button aria-pressed="false" data-audience="business">For your business</button></div><p class="hero-description" id="audience-description" aria-live="polite">`);
home=home.replace('Let’s take care of your property.','Explore a little. Tell us what you need.');
home=home.replace('<section class="section wrap" id="process">','<section class="section wrap reveal" id="process">').replace('<section class="about-section"','<section class="about-section reveal"');
home=home.replace('Start with a free quote</button>','Start with a free quote</button>').replace('</div><div class="steps">','</div><div class="steps">');
home=home.replace(/<div class="hero-visual">[\s\S]*?<\/section>/,heroShowcase+'</section>');
home=home.replace(/<section class="section wrap reveal" id="process">[\s\S]*?<\/section>/,processAccordion);
home=home.replace('YOUR PROPERTY. OUR PRIORITY.','PLUMBING. HEATING. PROPERTY CARE.');
const graphic=flowPanel;
const pages={
 index:{title:'Good hands. Great results.',description:'Plumbing, heating and property maintenance. Explore the new TRST Maintenance design concept.',html:home},
 about:{title:'About TRST',description:'Get to know the proposed approach to property care at TRST Maintenance in Willenhall.',html:`${intro('A local name.<br><span>A personal approach.</span>','About TRST','Good property care starts with understanding the people who live and work there.')}<section class="wrap story-grid"><div class="story-image reveal"><img src="assets/plumber.jpg" alt="Plumber working on a kitchen tap" width="700" height="470"><span>THE DETAILS MAKE THE DIFFERENCE.</span></div><div class="story-text reveal"><p class="eyebrow">BASED IN WILLENHALL</p><h2>For the places<br>you depend on.</h2><p>Your home should feel comfortable. Your business needs to keep moving. And when something needs attention, you need a clear place to start.</p><p>TRST Maintenance’s service range brings together plumbing, heating, drainage and property improvements. From the everyday issue to a bigger plan, tell the team what your property needs.</p><a class="text-link" href="services.html">Find your service <span class="plus">+</span></a></div></section><section class="section wrap"><div class="section-heading reveal"><div><p class="eyebrow">THE APPROACH</p><h2>Good work starts<br>with a good conversation.</h2></div></div><div class="editorial-values">${[['Listen first.','Every property is different. The first step is understanding your priorities, your space and the problem you want to solve.'],['Make it clear.','Talk through the scope, access and next steps. Get the information you need before agreeing to the work.'],['Think it through.','A practical plan makes all the difference. Discuss the details that matter, from timing to how your property is used.']].map((v,i)=>`<article class="reveal"><span>0${i+1}</span><h3>${v[0]}</h3><p>${v[1]}</p></article>`).join('')}</div></section>${cta()}`},
 services:{title:'Our services',description:'Explore plumbing, heating, drainage, commercial and bathroom services from TRST Maintenance.',html:`<div class="services-opening">${intro('One property.<br><span>Plenty of possibilities.</span>','Our services','A small repair. A bigger improvement. Find a starting point that fits your property.')}${graphic}</div><section class="wrap section service-directory"><div class="directory-heading"><div><p class="eyebrow">FIND YOUR SERVICE</p><h2>What needs attention?</h2></div><div class="filter-buttons" role="group" aria-label="Filter services"><button data-filter="all" aria-pressed="true">All services</button><button data-filter="repairs" aria-pressed="false">Repairs</button><button data-filter="projects" aria-pressed="false">Projects</button><button data-filter="business" aria-pressed="false">Business</button></div></div><p id="filter-status" class="result-label" aria-live="polite">6 services to explore</p><div class="service-grid" id="service-grid">${cards()}</div></section>${cta()}`},
 process:{title:'How it works',description:'Explore a straightforward proposed journey from your first enquiry to agreeing the work.',html:`${intro('Less uncertainty.<br><span>More progress.</span>','How it works','An easier way to think about your project, from your first question to getting the details agreed.')}<section class="wrap process-explorer reveal"><div class="process-controls" role="tablist" aria-label="Project stages">${['Tell us about it','Work out a plan','Agree the details'].map((s,i)=>`<button role="tab" id="stage-${i}" aria-controls="stage-panel-${i}" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-stage="${i}"><span>0${i+1}</span>${s}<b aria-hidden="true">+</b></button>`).join('')}</div><div class="process-panels">${[
 ['Start with what you know.','You don’t need to diagnose the problem. A simple description is a useful starting point.',['What is happening, and where?','Is it a home or business?','What is your postcode?'],'message'],
 ['A little detail goes a long way.','Discuss what needs doing, any access requirements and whether a visit is needed to assess the work.',['Explain your priorities','Share timing or access constraints','Ask about the proposed scope'],'file'],
 ['Know the next step.','Before work begins, confirm the scope, quote and arrangements directly with the team.',['Review the scope and price','Agree a suitable time','Confirm how to prepare the property'],'check']
 ].map((s,i)=>`<article id="stage-panel-${i}" role="tabpanel" aria-labelledby="stage-${i}" tabindex="0" ${i?'hidden':''}><div class="stage-graphic">${icon(s[3])}<span>0${i+1}</span></div><h2>${s[0]}</h2><p>${s[1]}</p><ul>${s[2].map(x=>`<li>${icon('check')}${x}</li>`).join('')}</ul></article>`).join('')}</div></section><section class="section wrap"><div class="preparation reveal"><div><p class="eyebrow">A USEFUL HEAD START</p><h2>A clearer brief.<br>A better conversation.</h2></div><p>Have your postcode, a description of the job and any timing requirements ready. For bigger projects, think about what you’d like to change and what matters most to you.</p></div></section>${cta()}`},
 reviews:{title:'Customer feedback',description:'A dedicated place for verified TRST customer feedback, with no invented testimonials.',html:`${intro('The people.<br><span>Behind the projects.</span>','Customer feedback','Choosing someone to work on your property is personal. Real customer experiences should be part of that decision.')}<section class="wrap feedback-layout"><div class="feedback-placeholder reveal"><span class="quote-symbol" aria-hidden="true">“</span><p class="eyebrow">REAL VOICES BELONG HERE</p><h2>Good feedback<br>is worth sharing.</h2><p>Verified customer stories will be added here once supplied and approved by TRST.</p><span class="concept-label">Design concept · Customer reviews pending</span></div><div class="feedback-aside reveal"><p class="eyebrow">WHILE YOU GET TO KNOW US</p><h3>Make an informed choice.</h3><p>Explore the services, understand the proposed process and speak to the team about your property.</p><a href="services.html">Explore the service range <span>+</span></a><a href="process.html">See how an enquiry works <span>+</span></a><a href="contact.html">Have a conversation <span>+</span></a></div></section>${cta()}`},
 faq:{title:'Frequently asked questions',description:'Answers about services, quote requests and planning your property work.',html:`${intro('Good questions.<br><span>Clearer answers.</span>','Frequently asked questions','A little clarity before you get started. Search below, or talk to the team about your specific needs.')}<section class="wrap faq-page"><aside class="faq-sidebar reveal"><label for="faq-search">Find an answer</label><div class="search-field">${icon('message')}<input type="search" id="faq-search" placeholder="Try “quote” or “postcode”" autocomplete="off"></div><p id="faq-status" aria-live="polite">9 answers to explore</p><div class="sidebar-help"><h3>Let’s talk it through.</h3><p>Some questions are better answered in a conversation.</p><a href="tel:+441902635925">01902 635925</a></div></aside><div class="faqs searchable-faqs">${faqs.map(([category,q,a])=>`<details class="reveal" data-faq><summary><span class="faq-question"><small>${category}</small>${q}</span><span>+</span></summary><p>${a}</p></details>`).join('')}<div id="faq-empty" hidden><h3>No matching answers.</h3><p>Try a different word or call the team.</p><button class="button outline" id="clear-search">Show all questions</button></div></div></section>${cta()}`},
 contact:{title:'Contact TRST',description:'Contact TRST Maintenance in Willenhall by phone, email or a demonstration quote enquiry.',html:`${intro('Big plans?<br><span>Small problem?</span>','Contact TRST','Either way, we’d like to hear about it. Choose the way that works for you.')}<section class="wrap contact-page"><div class="contact-methods reveal"><a class="contact-method" href="tel:+441902635925"><div class="method-icon">${icon('phone')}</div><small>LET’S TALK</small><h2>01902 635925</h2><p>Discuss the job and current availability.</p></a><a class="contact-method" href="mailto:info@trst-maintenance.co.uk"><div class="method-icon">${icon('message')}</div><small>WRITE TO THE TEAM</small><h2>info@trst-maintenance.co.uk</h2><p>Tell us about your property or project.</p></a><div class="location-card"><div>${icon('pin')}<small>WILLENHALL, WEST MIDLANDS</small></div><h3>Local roots.<br>Practical know-how.</h3><p>149 Stringes Lane<br>Willenhall, WV13 1LW</p><a href="https://www.google.com/maps/search/?api=1&query=149%20Stringes%20Lane%20Willenhall%20WV13%201LW" target="_blank" rel="noopener noreferrer">View address on Google Maps <span aria-hidden="true">↗</span></a></div></div><div class="contact-start reveal"><p class="eyebrow">START WITH YOUR PROJECT</p><h2>Let’s take care<br>of the details.</h2><p>A few quick questions help set the conversation in the right direction.</p><ol><li><span>01</span>Choose your service</li><li><span>02</span>Tell us about the job</li><li><span>03</span>Add your contact details</li></ol><button class="button full" data-quote>Start a free quote request</button><p class="contact-demo">Pitch prototype: the form demonstrates the journey. It does not send an enquiry.</p></div></section><section class="section wrap"><div class="preparation reveal"><div><p class="eyebrow">NEED HELP SOONER?</p><h2>Start with a call.</h2></div><div><p>For urgent requests, speak to the team directly to discuss the situation and confirm availability.</p><a class="text-link" href="tel:+441902635925">Call 01902 635925 ${icon('phone')}</a></div></div></section>`}
};
services.forEach((s,i)=>{pages['service-'+s.slug]={title:s.name,description:s.short,html:`<section class="wrap service-detail-hero"><div><div class="breadcrumbs"><a href="index.html">Home</a><span>/</span><a href="services.html">Services</a><span>/</span><span>${s.name}</span></div><p class="eyebrow">SERVICE / 0${i+1}</p><h1>${serviceHeading(s.name)}</span></h1><p>${s.intro}</p><button class="button" data-quote-service="${escape(s.name)}">Discuss this service</button></div><div class="detail-service-art reveal"><div class="detail-icon">${icon(s.icon)}</div><span class="art-number">0${i+1}</span><div class="art-bottom"><span>TRST MAINTENANCE</span><span>CARE IN EVERY DETAIL</span></div></div></section><section class="section wrap detail-content"><div class="reveal"><p class="eyebrow">A PLACE TO START</p><h2>What’s on<br>your list?</h2><p class="body-muted">Explain what you need and discuss the scope with the team. Availability and suitability are confirmed as part of your enquiry.</p></div><div class="scope-list">${s.items.map((x,j)=>`<article class="reveal"><span>0${j+1}</span><h3>${x}</h3>${icon('check')}</article>`).join('')}${s.note?`<p class="scope-note">${s.note}</p>`:''}</div></section><section class="detail-next"><div class="wrap preparation reveal"><div><p class="eyebrow">BEFORE WE SPEAK</p><h2>Help us see<br>the whole picture.</h2></div><div><p>Share your postcode, the type of property and a description of the work. Include any access arrangements or timing requirements.</p><a class="text-link" href="process.html">Explore the next steps <span class="plus">+</span></a></div></div></section><section class="section wrap"><div class="section-heading"><div><p class="eyebrow">WHILE YOU’RE HERE</p><h2>More ways to help.</h2></div><a class="text-link" href="services.html">View all services <span class="plus">+</span></a></div><div class="service-grid related-grid">${cards([services[(i+1)%6],services[(i+2)%6],services[(i+3)%6]])}</div></section>${cta()}`};});
for(const [key,page] of Object.entries(pages)){
 let html=template.replace(/<title>.*?<\/title>/,`<title>${page.title} | TRST Maintenance</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${escape(page.description)}">`).replace(/<main id="main">[\s\S]*?<\/main>/,`<main id="main">${page.html}</main>`);
 html=html.replace(/<nav class="desktop-nav"[\s\S]*?<\/nav>/,`<nav class="desktop-nav" aria-label="Main navigation">${nav(key.startsWith('service-')?'services':key)}</nav>`).replace(/<nav id="mobile-nav"[\s\S]*?<\/nav>/,`<nav id="mobile-nav" class="mobile-nav" aria-label="Mobile navigation" hidden>${nav(key.startsWith('service-')?'services':key)}<button class="button" data-quote>Get a free quote</button></nav>`);
 if(key.startsWith('service-')){const index=services.findIndex(s=>'service-'+s.slug===key);html=html.replace(/<div class="detail-service-art reveal">[\s\S]*?<\/div><\/section>/,detailPhoto(index)+'</section>');}
 html=html.replace('The photography is reused from that site for this concept and is not verified project photography.','Photography combines images from the original website with AI-generated service illustrations. None is presented as verified TRST project photography.');
 html=refinePage(key,html);
 html=html.replace('</head>','<link rel="stylesheet" href="refinements.css"></head>');
 html=html.replace('</body>','<script src="motion.js"></script><script src="refinements.js"></script></body>');
 await writeFile(new URL(`dist/${key}.html`,import.meta.url),html);
}
await writeFile(new URL('dist/styles.css',import.meta.url),await readFile(new URL('src/styles.css',import.meta.url)));
await writeFile(new URL('dist/enhancements.css',import.meta.url),await readFile(new URL('src/enhancements.css',import.meta.url)));
await writeFile(new URL('dist/app.js',import.meta.url),await readFile(new URL('src/app.js',import.meta.url)));
await writeFile(new URL('dist/visuals.css',import.meta.url),await readFile(new URL('src/visuals.css',import.meta.url)));
await writeFile(new URL('dist/motion.js',import.meta.url),await readFile(new URL('src/motion.js',import.meta.url)));
console.log(`Built ${Object.keys(pages).length} static pages.`);
for(const file of ['refinements.css','refinements.js']) await writeFile(new URL(`dist/${file}`,import.meta.url),await readFile(new URL(`src/${file}`,import.meta.url)));

