const icon=name=>`<svg class="icon" aria-hidden="true"><use href="#i-${name}"/></svg>`;
export const stepImages=['step-enquiry.svg','step-plan.svg','step-agree.svg'];
const stepAlts=['Describe your property and the issue in an enquiry','Review the work, property plan and access requirements','Confirm the quote, scope and a suitable appointment'];
const stepCaptions=['Tell us what you know.','Work through the possibilities.','Know what happens next.'];
const stepVisual=(i)=>`<img src="assets/${stepImages[i]}" alt="Illustration: ${stepAlts[i]}" width="800" height="560" loading="lazy">`;
const selectCards=(title,description,choices)=>`<section class="wrap section service-tool"><div class="tool-heading"><p class="eyebrow">MAKE THE CONVERSATION COUNT</p><h2>${title}</h2><p>${description}</p></div><div class="choice-guide"><div class="choice-buttons" role="group" aria-label="Choose your situation">${choices.map((c,i)=>`<button data-guide-choice="${i}" aria-pressed="${!i}" aria-controls="guide-result"><span>0${i+1}</span>${c[0]}${icon('drop')}</button>`).join('')}</div><div class="choice-result" id="guide-result" aria-live="polite">${choices.map((c,i)=>`<article data-guide-panel="${i}" ${i?'hidden':''}><p class="eyebrow">YOUR ENQUIRY STARTER</p><h3>${c[1]}</h3><p>${c[2]}</p><a class="text-link" href="contact.html">Discuss your property <span>↗</span></a></article>`).join('')}</div></div></section>`;
const checklist=(title,items)=>`<div class="brief-checklist"><h3>${title}</h3><p>Select the details you have ready.</p>${items.map(x=>`<label><input type="checkbox" data-brief-check><span>${x}</span></label>`).join('')}<p class="check-progress" aria-live="polite">0 of ${items.length} details ready</p></div>`;
const serviceExtras={
 'plumbing-repairs':()=>selectCards('Where does it need attention?','Choose a starting point to see what is useful to tell the team.',[
 ['Taps & sinks','Describe the fixture and the symptoms.','Is the issue at the tap, beneath the sink or around a fitting? Mention when it started and whether it happens all the time.'],
 ['Toilets','Explain what has changed.','Tell the team whether the issue is with flushing, filling or water appearing around the fixture. Include how many toilets are affected.'],
 ['Pipework','Share the location and access.','Describe where you have noticed the issue, whether the pipework is visible and which rooms are affected. You do not need to identify the cause.']]),
 'heating-cooling':()=>`<section class="wrap section comfort-guide"><div><p class="eyebrow">COMFORT, CONSIDERED</p><h2>Different systems.<br>Different questions.</h2><p>Knowing the system and the symptoms helps the team confirm whether they can help.</p><div class="comfort-columns"><article>${icon('heat')}<h3>Heating</h3><p>Mention the affected rooms, radiator or system type, and whether the issue is constant or intermittent.</p></article><article>${icon('house')}<h3>Cooling</h3><p>Share the equipment make and model if known, where it is installed and what has changed in its operation.</p></article></div></div><figure><img src="assets/cooling-service.png" alt="AI illustration of cooling-system maintenance" width="1536" height="1024" loading="lazy"><figcaption>AI service illustration · Not a TRST project</figcaption></figure></section>`,
 'drain-repairs':()=>selectCards('One drain or a recurring problem?','A useful description begins with what you can observe.',[
 ['One fixture','Start with the affected fixture.','Which sink, shower or other fixture is draining slowly? Mention whether it is a new problem and how frequently it happens.'],
 ['Several fixtures','Explain the wider pattern.','List the fixtures affected and whether the symptoms happen at the same time. Mention any previous assessments you can share with the team.'],
 ['Outside drainage','Describe the location.','Say whether the issue is at an outside drain, gully or another area of the property. Mention access restrictions and any assessment already carried out.']]),
 'commercial-plumbing':()=>`<section class="business-brief"><div class="wrap business-brief-grid"><div><p class="eyebrow">PLAN AROUND YOUR PREMISES</p><h2>Keep the practical<br>details in view.</h2><p>A clear facilities brief helps the team discuss the work alongside your day-to-day operations.</p><div class="business-milestones"><article><span>01</span><h3>The premises</h3><p>Building type, affected facilities and who can authorise the work.</p></article><article><span>02</span><h3>The working day</h3><p>Opening hours, busy periods and preferred access arrangements.</p></article><article><span>03</span><h3>The scope</h3><p>Repairs, planned changes or a maintenance enquiry. Confirm suitability with the team.</p></article></div></div>${checklist('Build your facilities brief',['Site address and postcode','Affected fixtures or facilities','Access contact and opening hours','Timing and operational constraints'])}</div></section>`,
 'bathroom-remodelling':()=>`<section class="wrap section bathroom-planner"><div><p class="eyebrow">START WITH HOW YOU USE THE SPACE</p><h2>Your bathroom.<br>Your priorities.</h2><p>Select what matters to you. Use these prompts when discussing your project with the team.</p><div class="priority-options" role="group" aria-label="Bathroom priorities">${['Replace tired fittings','Improve the layout','Make access easier','Update the look'].map(x=>`<button data-priority aria-pressed="false">${icon('bath')}${x}<span>+</span></button>`).join('')}</div><p class="priority-summary" aria-live="polite">Choose one or more priorities to shape your brief.</p></div><aside><p class="eyebrow">BEFORE CHOOSING FINISHES</p><h3>Think beyond the surface.</h3><ol><li><strong>What stays?</strong><p>Identify the fittings and features you would like to keep.</p></li><li><strong>What changes?</strong><p>Describe any proposed layout, fixture or access improvements.</p></li><li><strong>What needs confirming?</strong><p>Discuss feasibility, the plumbing scope, budget and timing before committing.</p></li></ol></aside></section>`,
 'gas-line-services':()=>`<section class="wrap section gas-enquiry"><div class="gas-heading"><p class="eyebrow">A CAREFUL START</p><h2>Confirm the scope.<br>Confirm the professional.</h2><p>Gas work requires the appropriate qualifications for the specific work. Ask the team to confirm who will carry it out and how to verify their registration before booking.</p><a class="text-link" href="contact.html">Discuss a planned enquiry <span>↗</span></a></div><div class="gas-questions"><article><span>01</span><h3>What work is proposed?</h3><p>Describe the pipework, appliance or project involved, and the property type.</p></article><article><span>02</span><h3>Who will carry it out?</h3><p>Confirm the named professional and their Gas Safe registration and relevant categories of work.</p></article><article><span>03</span><h3>What is included?</h3><p>Agree the assessment, scope, quote and any documentation with the team.</p></article><p class="scope-note">This page supports planned enquiries. It is not an emergency reporting service or an installation guide.</p></div></section>`
};
export function refinePage(key,html){
 if(key==='index'){
  html=html.replace(/<div class="audience-switch"[\s\S]*?<\/div>/,`<div class="audience-switch" role="group" aria-label="Choose property type">${[['home','house','For your home','Everyday care & bigger plans'],['business','building','For your business','Premises & practical support']].map(([v,i,t,s])=>`<button aria-pressed="${v==='home'}" data-audience="${v}">${icon(i)}<span><strong>${t}</strong><small>${s}</small></span><b aria-hidden="true">↗</b></button>`).join('')}</div>`);
  html=html.replace(/<div class="wrap values">[\s\S]*?<\/div><\/section>/,`<div class="wrap values">${[['house','Homes & businesses','Care for the places you depend on.','services.html'],['message','A clear conversation','Start with your property and priorities.','process.html'],['file','Explore your options','Understand the scope before booking.','faq.html'],['tool','Repairs to renovations','From everyday issues to bigger plans.','services.html']].map(([i,t,s,url])=>`<a href="${url}" class="benefit-card">${icon(i)}<div><strong>${t}</strong><span>${s}</span></div><b aria-hidden="true">↗</b></a>`).join('')}</div></section>`);
  html=html.replace(/<div class="process-illustration">[\s\S]*?<\/div><\/div>/,`<div class="process-visuals" aria-live="polite">${stepImages.map((_,i)=>`<figure class="step-scene ${!i?'is-active':''}" data-step-scene="${i}" ${i?'hidden':''}>${stepVisual(i)}<figcaption><span>0${i+1} / THE NEXT STEP</span><strong>${stepCaptions[i]}</strong></figcaption></figure>`).join('')}<span class="illustration-label">Process illustrations · Proposed journey</span></div>`);
  html=html.replace(/(<div class="process-accordion-panel" id="home-panel-(\d)"[^>]*><div>)/g,(_m,start,i)=>`${start}<figure class="mobile-step-visual">${stepVisual(Number(i))}<figcaption>${stepCaptions[Number(i)]}</figcaption></figure>`);
 }
 if(key==='process'){
  html=html.replace(/<div class="stage-graphic">[\s\S]*?<\/div>/g,(()=>{let n=0;return ()=>`<div class="stage-visual">${stepVisual(n++)}</div>`})());
  html=html.replace('<section class="section wrap"><div class="preparation',`<section class="wrap section journey-preparation">${checklist('Ready for that first conversation?',['Property postcode','Description of the work','Home or business','Timing and access requirements'])}<div><p class="eyebrow">NO NEED TO HAVE EVERY ANSWER</p><h2>Start with<br>what you know.</h2><p>These prompts help organise your enquiry. The team can discuss anything that still needs working out.</p><button class="button" data-quote>Try the enquiry journey</button></div></section><section class="section wrap"><div class="preparation`);
 }
 if(key==='services'){
  html=html.replace('<section class="wrap section service-directory">',`<section class="wrap service-finder"><p class="eyebrow">FOLLOW THE PROBLEM</p><h2>Not sure where to start?</h2><div>${[['A leak or dripping tap','plumbing-repairs'],['An uncomfortable room','heating-cooling'],['Water draining slowly','drain-repairs'],['Changes at work','commercial-plumbing']].map(([t,s])=>`<a href="service-${s}.html">${t}<span>↗</span></a>`).join('')}</div></section><section class="wrap section service-directory">`);
 }
 if(key==='faq'){
  html=html.replace('<div class="sidebar-help">',`<div class="faq-topics" role="group" aria-label="Filter questions by topic">${['All','Services','Planning','Quotes'].map(t=>`<button data-faq-topic="${t}" aria-pressed="${t==='All'}">${t}</button>`).join('')}</div><div class="sidebar-help">`);
 }
 if(key==='about'){
  html=html.replace('<section class="section wrap">',`<section class="wrap local-story"><div><p class="eyebrow">WILLENHALL / WEST MIDLANDS</p><h2>One place to start.<br>For the place you call yours.</h2></div><div><p>Based at 149 Stringes Lane, TRST brings together plumbing and property service enquiries for homes and commercial premises.</p><p>Share your postcode and the work you have in mind so the team can confirm coverage and suitability.</p><a class="text-link" href="contact.html">Find the team ${icon('pin')}</a></div></section><section class="section wrap">`);
 }
 if(key==='reviews'){
  html=html.replace('<section class="wrap page-cta',`<section class="wrap section feedback-guide"><div><p class="eyebrow">A USEFUL WAY TO COMPARE</p><h2>Look for the details<br>behind a review.</h2><p>While verified TRST feedback is pending, these questions can help you evaluate any property service.</p></div><div class="faqs">${[['Was the work similar?','Look for experiences that describe the same type of property and work you have in mind. Context is more useful than a score alone.'],['Was the scope clear?','Ask how the work, quote and timing were explained, and how any changes were discussed.'],['Can the source be checked?','Use the original source where possible. No ratings or customer quotes are presented here until genuine feedback is supplied and approved.']].map(([q,a])=>`<details><summary>${q}<span>+</span></summary><p>${a}</p></details>`).join('')}</div></section><section class="wrap page-cta`);
 }
 if(key.startsWith('service-')){
  const slug=key.slice(8);
  html=html.replace('<section class="detail-next">',`${serviceExtras[slug]?.()||''}<section class="detail-next">`);
 }
 // Hero service provenance remains visible; About imagery is documented in the prototype dialog.
 html=html.replace('<span class="showcase-label">TRST / CARE IN EVERY DETAIL</span>','<span class="showcase-label">SERVICE IMAGERY · NOT VERIFIED TRST WORK</span>');
 // Native details remain usable without JavaScript; body wrapper enables closing animation.
 html=html.replace(/(<details\b[^>]*>)([\s\S]*?<\/summary>)([\s\S]*?)(<\/details>)/g,(_m,start,summary,body)=>`${start}${summary}<div class="faq-answer"><div class="faq-water" aria-hidden="true"><svg viewBox="0 0 60 140"><path class="faq-pipe" d="M12 0v95q0 18 18 18h28"/><path class="faq-stream" pathLength="100" d="M12 0v95q0 18 18 18h28"/></svg></div><div class="faq-answer-copy">${body}</div></div></details>`);
 return html.replace('<body>','<body data-page="'+key+'">');
}
