const svg = name=>`<svg class="icon" aria-hidden="true"><use href="#i-${name}"/></svg>`;
export const photos=[
 ['plumber.jpg','Repairing a kitchen tap'],
 ['heating-service.png','Illustrative heating engineer working on radiator pipework'],
 ['drainage-service.png','Illustrative technician cleaning an exterior drain'],
 ['commercial-plumbing.svg','Illustration of commercial washroom plumbing and water distribution'],
 ['bathroom-service.png','Illustrative contemporary bathroom renovation concept'],
 ['gas-services.svg','Concept illustration of a gas meter, isolation valve and copper supply pipe']
];
const provenance=index=>index===0?'Original website image · Project unverified':index===3||index===5?'Service illustration · Not a TRST project':'AI illustration · Not a TRST project';
export function photoCard(service,index){const photo=photos[index];return `<article class="service-card photo-service reveal" data-category="${service.category}"><a class="service-photo" href="service-${service.slug}.html" tabindex="-1" aria-hidden="true"><img src="assets/${photo[0]}" alt="" width="768" height="512" loading="lazy"><span class="photo-number">0${index+1} / SERVICE OVERVIEW</span><span class="photo-open">Explore <span aria-hidden="true">+</span></span></a><div class="service-card-copy"><span class="image-provenance">${provenance(index)}</span><h3>${service.name}</h3><p>${service.short}</p><a class="text-link service-link" href="service-${service.slug}.html" aria-label="Explore ${service.name}">Explore service <span class="plus" aria-hidden="true">+</span></a></div></article>`}
export function detailPhoto(index){const p=photos[index];return `<div class="service-detail-photo reveal"><img src="assets/${p[0]}" alt="${p[1]}" width="1536" height="1024" fetchpriority="high"><div class="service-photo-caption"><span>${provenance(index)}</span><strong>See the service.<br>Plan the next step.</strong></div><span class="detail-photo-number">0${index+1}</span></div>`}
export const heroShowcase=`<div class="hero-showcase" aria-roledescription="carousel" aria-label="Explore our property services"><div class="hero-photo-stage">${[
 ['plumber.jpg','Plumbing & repairs','Everyday problems.<br>Expert attention.','service-plumbing-repairs.html','Plumbing repair on a kitchen tap'],
 ['heating-service.png','Heating & cooling','Comfort starts<br>with good care.','service-heating-cooling.html','Illustrative heating maintenance'],
 ['bathroom-service.png','Bathroom & remodelling','Fresh thinking.<br>Better spaces.','service-bathroom-remodelling.html','Illustrative bathroom renovation concept']
].map((p,i)=>`<figure class="hero-slide ${i===0?'active':''}" data-slide="${i}" ${i?'aria-hidden="true" inert':''}><img src="assets/${p[0]}" alt="${p[4]}" width="1536" height="1024" ${i?'loading="lazy"':'fetchpriority="high"'}><figcaption><span>${p[1]}</span><h2>${p[2]}</h2><a href="${p[3]}">Explore this service <span aria-hidden="true">+</span></a></figcaption></figure>`).join('')}<span class="showcase-label">TRST / CARE IN EVERY DETAIL</span></div><div class="showcase-controls"><span class="slide-count" aria-live="polite">01 <span>/ 03</span></span><div class="slide-dots" role="group" aria-label="Choose service image">${[1,2,3].map((n,i)=>`<button data-slide-to="${i}" aria-label="Show service image ${n}" aria-pressed="${i===0}"><span></span></button>`).join('')}</div><button class="carousel-pause" aria-label="Pause service slideshow" aria-pressed="false"><span data-play-symbol aria-hidden="true">Ⅱ</span><span data-play-label>Pause</span></button></div><div class="hero-pipe-caption"><svg viewBox="0 0 340 28" aria-hidden="true"><path class="pipe-track" d="M4 14H336"/><path class="water-current" d="M4 14H336"/></svg><span>Keeping your property flowing.</span></div></div>`;
export const flowPanel=`<div class="flow-panel reveal"><div class="flow-heading"><span>YOUR PROPERTY, CONNECTED</span><button class="flow-toggle" aria-pressed="false">Pause flow</button></div><svg class="plumbing-diagram" viewBox="0 0 560 360" role="img" aria-labelledby="flow-title flow-desc"><title id="flow-title">Plumbing, heating and drainage service diagram</title><desc id="flow-desc">Animated water paths connect a property to plumbing, heating and drainage. The service links below open more information.</desc><defs><linearGradient id="water-tone"><stop stop-color="#63d7ff"/><stop offset="1" stop-color="#7b92ff"/></linearGradient></defs><g fill="none" stroke-linecap="round" stroke-linejoin="round"><path class="pipe-outline" d="M65 52V138Q65 158 85 158H236Q260 158 260 182V250Q260 273 283 273H491M260 182V92Q260 72 280 72H454M65 158V255Q65 273 84 273H167"/><path class="pipe-track" d="M65 52V138Q65 158 85 158H236Q260 158 260 182V250Q260 273 283 273H491M260 182V92Q260 72 280 72H454M65 158V255Q65 273 84 273H167"/><path class="water-current" d="M65 52V138Q65 158 85 158H236Q260 158 260 182V250Q260 273 283 273H491"/><path class="water-current warm-current" d="M260 182V92Q260 72 280 72H454"/><path class="water-current" d="M65 158V255Q65 273 84 273H167"/><circle class="valve-ring" cx="158" cy="158" r="23"/><g class="valve-wheel"><path d="M140 140L176 176M140 176L176 140"/></g></g><g class="diagram-node"><rect x="32" y="17" width="66" height="49" rx="10"/><use href="#i-drop" x="51" y="26" width="28" height="30"/><rect x="432" y="42" width="66" height="60" rx="10"/><use href="#i-heat" x="451" y="57" width="28" height="30"/><rect x="464" y="244" width="66" height="60" rx="10"/><use href="#i-drain" x="483" y="259" width="28" height="30"/><rect x="142" y="244" width="64" height="60" rx="10"/><use href="#i-house" x="160" y="259" width="28" height="30"/></g><g class="diagram-labels"><text x="113" y="46">PLUMBING</text><text x="379" y="120">HEATING</text><text x="411" y="330">DRAINAGE</text><text x="118" y="330">YOUR PROPERTY</text></g></svg><div class="flow-links"><a href="service-plumbing-repairs.html">Plumbing <span>+</span></a><a href="service-heating-cooling.html">Heating <span>+</span></a><a href="service-drain-repairs.html">Drainage <span>+</span></a></div></div>`;
export const processAccordion=`<section class="home-process"><div class="wrap process-story"><div class="process-story-left"><p class="eyebrow">A SIMPLE WAY FORWARD</p><h2>Three steps.<br><span>One less worry.</span></h2><p>From that first “can you help?” to a plan that works for your property.</p><div class="process-illustration"><img src="assets/heating-service.png" alt="Illustrative heating engineer working carefully on pipework" width="1536" height="1024" loading="lazy"><div><span class="process-live-number">01</span><span>LET’S GET<br>THINGS MOVING.</span></div></div></div><div class="process-accordion">${[
 ['Tell us what needs doing.','A quick repair or a bigger project? Tell us what’s happening, where it is and what you have in mind.','Start with a free quote'],
 ['Let’s work out a plan.','Discuss the scope, access and timing. Ask your questions and understand the proposed work before agreeing to it.','Talk through your project'],
 ['Get the details sorted.','Confirm the quote and a suitable time directly with the team. Know what to expect and how to prepare your property.','Get your project started']
].map((p,i)=>`<article class="process-accordion-item ${i===0?'is-open':''}"><h3><button id="home-step-${i}" class="process-accordion-trigger" aria-expanded="${i===0}" aria-controls="home-panel-${i}" data-home-step="${i}"><span class="step-token">0${i+1}</span><span>${p[0]}</span><b aria-hidden="true">+</b></button></h3><div class="process-accordion-panel" id="home-panel-${i}" role="region" aria-labelledby="home-step-${i}" ${i?'hidden':''}><div><p>${p[1]}</p><button class="text-link" data-quote>${p[2]} <span class="plus">+</span></button></div></div></article>`).join('')}<a class="process-all-link" href="process.html">Explore the full journey <span>+</span></a></div></div></section>`;
